### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by aroben** [electron/brightray_example#6]
I'd like to make brightray_example work on Windows. This will depend on aroben/brightray#11.
### To do
- [x] Rewrite scripts in Python (#9)
- [x] Get a basic build working (#10)
- [x] Write Windows equivalents of Mac-specific code (#11)
